<nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
  <div class="container-fluid">
<a class="navbar-brand active" href="index.html">Literacy Report Cards</a>
 <ul class="nav navbar-nav">
<li><a href="changes.html">Change Over Time</a></li>
<li><a href="about.html">About</a></li>
</ul>
</nav></div>

<div class="container">
<div class="row">
<div class="col-md-12" role="main">

```{r results='asis', cache=TRUE, echo=FALSE, warning=FALSE, message=FALSE, out.extra="", fig.height=5, fig.width=10, dpi=100, fig.align='center'}
## FUNCTIONS AND IMPORTS
require(plyr); require(reshape2); require(ggplot2); require(xtable); require(scales); require(stringr)
learningdata <- readRDS("data/Learning_processed.RDS")

## Two level aggregation; we need to figure out, for each (group, treatment, class, phase)
## what the percent of children in a given literacy level among all levels is.
summaries <- ddply(learningdata, c("Phase", "Group", "grade", "treat"), function(df) {
    total_in_higher_group <- nrow(df)
    ddply(df, "literacy_level", function(df) {
        total = nrow(df)
        data.frame(
          TotalInGroup = total,
          PercentOfGroup = total / total_in_higher_group
    )})
})
```

```{r results='asis', cache=TRUE, echo=FALSE, warning=FALSE, message=FALSE, out.extra="", fig.height=5, fig.width=10, dpi=100, fig.align='center'}
require(stringr)
### Tab headers
cat('<div id="content-wrapper" class="container container-fluid"><div id="tabs">\n<ul>\n')
grades <- unique(learningdata$grade)
cat(sprintf('<li><a href="#%s">%s</a></li>\n', str_replace(grades, ' ', ''), grades))
cat('</ul>\n')
```

```{r results='asis', cache=TRUE, echo=FALSE, warning=FALSE, message=FALSE, out.extra="", fig.height=2, fig.width=10, dpi=100, fig.align='center'}
## We want a separate tab per grade. Everything inside this d_ply is per-grade.
d_ply(summaries, "grade", function(df) {
    ## This div says that all of the following content belongs to this tab
    cat(sprintf('<div id="%s">', str_replace(df[1,'grade'], ' ', '')))
    
    ## First, we show the denominator for the percents people are looking at
    cat('<h5>Total number of Assessments:</h5>')
    phasetotals <- ddply(df, "Phase", summarize, Total=sum(TotalInGroup))
    cat(sprintf("%s: %s     ", phasetotals$Phase, phasetotals$Total))
    
    
    ## Graphs for the grade
    d_ply(df, "literacy_level", function(df_inner) {
        literacy_level <- df_inner[1,'literacy_level']
        
        ## Instead of using faceting, we make an HTML h5 label for each literacy level
        cat('<div class="row"><div class="col-md-1">')
        cat(sprintf('<h5> %s: </h5>', literacy_level))
        cat('</div>')
        
        ## Now we output the graph to the right. Note that coloring has to be manual
        cat('<div class="col-md-8">')
        fillcolor = c("Nothing"="#d7191c", "Letters" ="#ef8a62", "Words"="#ffffbf",
                      "Paragraphs"="#abd9e9", "Story"="#2c7bb6")[literacy_level]
        print(ggplot(data=df_inner, aes(x=Phase, y=PercentOfGroup)) + 
            geom_bar(stat='identity', fill=fillcolor) + facet_grid(~ treat) + 
            scale_y_continuous(labels=percent) + labs(x="", y="Percent") +
            theme_minimal())
        cat('</div></div>')
    })
    ## A little explainer, after which we can close the div for this grade-tab
    cat(sprintf('Note: percents refer to percentage across literacy levels.
                For example, out of all children in %s grade in the Control group
                assessed during Baseline, only %s percent could read a Story.',
                unique(df$grade),
                round(100 * subset(df, treat=='Control' & Phase=='Baseline'
                                   & literacy_level=='Story')$PercentOfGroup)
                ))        
    cat('\n</div>\n')
})
```

<br/><br/><br/>
</div></div></div>
<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" type="text/css" media="screen,projection" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script type="text/javascript"> (function($) { $( "#tabs" ).tabs(); })(jQuery); </script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">